### PR TITLE
Include all state and territory government sites, list by population.

### PR DESCRIPTION
**Pull request by MrChrisW**
Hi @fukawi2, 

I've sorted state government information by [population](http://en.wikipedia.org/wiki/Ranked_list_of_states_and_territories_of_Australia#By_population) and included the following states/territories 
- Western Australia
- South Australia
- Tasmania
- Northern Territory

### CODE REVIEW

**Comment by fukawi2** [comment]
Love your work! I'll review fully and merge it as soon as I get back to a
computer.

**Comment by MrChrisW** [comment]
No problem, love the Australian fork of HTTPSWatch you've made! :smile:

**Comment by fukawi2** [comment]
Thanks again for the contribution. I've merged, and I'll update the site shortly.

**Comment by MrChrisW** [comment]
@fukawi2 Sweet, thanks.

**Comment by cybershambles** [comment]
Thanks.

**Pull request merged**
